### PR TITLE
 UNOMI-212: Added Running Unomi with Docker Tutorial to the Website

### PR DESCRIPTION
**Pull request by mikeghen**
* Added instructions for running Unomi with Docker to the tutorials page, put a link on the resources page

### CODE REVIEW

**Comment by mikeghen** [comment]
@fpapon, good catch, I removed them

**Comment by sergehuber** [comment]
Hello Michael, sorry I couldn't get back to you on this earlier.

I noticed something strange, and it's not the first time you contributed HTML code that had this problem but last time we corrected it on merge and forgot to give you feedback. You have the following multiple times in the HTML : 

            <code><pre>
docker-compose up
            </code></pre>

(note the code and pre tags are not closed in the right order). 

Would you mind correcting this ? 

Are you using a tool that's generating this this way ? 

Thanks,
Regards,
  Serge...

**Comment by mikeghen** [comment]
@sergehuber, good eyes! That was just a cut-and-paste error in my text editor. I resolved it

**Comment by sergehuber** [comment]
I have no merit I have an IDE that highlights HTML errors :)

**Comment by mikeghen** [comment]
That's something I might look into, sounds useful, lmk is there's anything else @sergehuber

**Comment by sergehuber** [comment]
Ok I merged the PR thanks a lot for your contributions !

**Pull request merged**
